// This file is automatically generated. Do not edit
extern unsigned int *courier_bold_36_length[95];
extern unsigned char *courier_bold_36_data[95];
extern unsigned int courier_bold_36_width;
extern unsigned int courier_bold_36_height;
