// This file is automatically generated. Do not edit
extern unsigned int *courier_bold_72_length[95];
extern unsigned char *courier_bold_72_data[95];
extern unsigned int courier_bold_72_width;
extern unsigned int courier_bold_72_height;
