// This file is automatically generated. Do not edit
extern unsigned int *dejavu_sans_mono_72_length[95];
extern unsigned char *dejavu_sans_mono_72_data[95];
extern unsigned int dejavu_sans_mono_72_width;
extern unsigned int dejavu_sans_mono_72_height;
